### ISSUE TITLE
Governance Submission

### ISSUE THREAD

**Issue by iboss-ptk** [osmosis-labs/beaker#12]
## Todo
- [x] try osimosisd  to go through the process
- [x] start with gov store-code
  - [x] reconstruct this msg in rust `https://github.com/CosmWasm/wasmd/blob/ac92fdcf37388cc8dc24535f301f64395f8fb3da/proto/cosmwasm/wasm/v1/proposal.proto` and try rpc-ing it
  - [x] make gov proposal works
  - [x] refactor types -> gen types -> get path
  - [x] expose proposal related stuffs to the interface
  - [x] check mainnet config with command provided by Dev & see plan about gov
  - [BLOCKED] try editing `genesis.json` remove permission to test the process (with for nico / adam response)
  - [x] fix state file: non has config for local and shared network
    - [x] serialize config for state variant
    - [x] get state variant from context (check by network)
    - [x] update state file based on state variant (pass as arg)
  - [x] `PropsoalStoreCodeResponse`
  - [x] make deposit works (for today: 7 Jun)
  - [x] check deposit
  - [x] extract module
  - [x] update state for proposal
    - [x] make code_id optional
    - [x] add proposal_id
    - [x] add update_proposal_id function
  - [x] find the hash function for code_hash -> sha256sum
  - [x] create query for proposal
  - [x] refactor: extract modules
  - [x] move ops into their own module

  - [x]  `beaker wasm proposal vote store-code counter  --amount 10000uosmo {{base_tx}}`
    - [x] create proposal/ops/vote.rs
    - [x] copy code from store code
    - [x] get the right message in, make sure code compiles
      - [x] get_ref . proposal_store_code_id to query
    - [x] update entry point with respective stuffs needed

  - [x] `beaker wasm proposal store-code sync-state`
    - [x] `update_in!` for handling nested struct (see [[1]](https://docs.rs/im/latest/src/im/lib.rs.html#432-441), [[2]](https://github.com/DenisKolodin/match_cast/blob/master/src/lib.rs))
    - [x] new struct for proposal
```rust
// ultimately
struct Code {
  id: u64,
  instances: Map<String, String>
}

struct Proposal {
   store_code: Option<u64>
}

struct WasmRef {
    code: Option<Code>
    proposal: Proposal,
}
